version: '3.1'

services:
  webapp:
    image: "{{ image_name }}"
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - application

networks:
  application:
    external: true